### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by JPA1238** [RobinDeBaets/UforaFileFetcher#14]
Microsoft asks for email upon login instead of username so selenium can't find the tag username.

`
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="username"]"}
  (Session info: chrome=94.0.4606.81)
`

**Comment by RobinDeBaets** [comment]
This is fixed now. Email is to be used everywhere now instead of username. Will have to change your old config files (`"username"` -> `"email"`). See examples in readme.
